### ISSUE TITLE
Setup.py error

### ISSUE THREAD

**Issue by luuude** [Ascend-Research/Turtle#1]
When trying to install I am getting the following error:

Traceback (most recent call last):
  File "/content/Turtle/basicsr/setup.py", line 151, in <module>
    write_version_py()
  File "/content/Turtle/basicsr/setup.py", line 73, in write_version_py
    with open('VERSION', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'

**Comment by Amirhosein-gh98** [comment]
Hi,

I added the VERSION file. It should be fine now.
